INSERT INTO CUSTOMER (FIRST_NAME,LAST_NAME,EMAIL) VALUES ('Gokhan', 'Memis', 'gokhanmemis@gmail.com');
INSERT INTO CUSTOMER (FIRST_NAME,LAST_NAME,EMAIL) VALUES ('bce', 'Memis', 'bce@gmail.com');
INSERT INTO CUSTOMER (FIRST_NAME,LAST_NAME,EMAIL) VALUES ('cde', 'Memis', 'cde@gmail.com');
INSERT INTO CUSTOMER (FIRST_NAME,LAST_NAME,EMAIL) VALUES ('efg', 'Memis', 'efg@gmail.com');

INSERT INTO BOOK (BOOK_NAME,AUTHOR,ISBN,STOCK_SIZE,PRICE) VALUES ('Var Mısın? Güçlü Bir Yaşam İçin Öneriler', 'Doğan Cüceloğlu', '9786057635839',50,26.99);
INSERT INTO BOOK (BOOK_NAME,AUTHOR,ISBN,STOCK_SIZE,PRICE) VALUES ('Suç Ve Ceza', 'Fyodor Mihailoviç Dostoyevski', '9783863523756',50,12.9);
INSERT INTO BOOK (BOOK_NAME,AUTHOR,ISBN,STOCK_SIZE,PRICE) VALUES ('Kumarbaz', 'Fyodor Mihailoviç Dostoyevski', '9788420635491',50,7.9);
INSERT INTO BOOK (BOOK_NAME,AUTHOR,ISBN,STOCK_SIZE,PRICE) VALUES ('İnsan Neyle Yaşar?', 'Lev Nikolayeviç Tolstoy', '9783743709027',50,6.5);
INSERT INTO BOOK (BOOK_NAME,AUTHOR,ISBN,STOCK_SIZE,PRICE) VALUES ('Romeo ve Juliet', 'William Shakespeare', '9780563553441',50,7.5);
INSERT INTO BOOK (BOOK_NAME,AUTHOR,ISBN,STOCK_SIZE,PRICE) VALUES ('Bir İdam Mahkumunun Son Günü', 'Victor Hugo', '9783863524128',50,5.90);

INSERT INTO BOOK_ORDER  (BOOK_ID,CUSTOMER_ID,ORDER_DATE,QUANTITY) VALUES (2, 1, '2021-01-01',5);
INSERT INTO BOOK_ORDER  (BOOK_ID,CUSTOMER_ID,ORDER_DATE,QUANTITY) VALUES (1, 1, '2021-02-01',6);
INSERT INTO BOOK_ORDER  (BOOK_ID,CUSTOMER_ID,ORDER_DATE,QUANTITY) VALUES (2, 1, '2021-03-01',7);
INSERT INTO BOOK_ORDER  (BOOK_ID,CUSTOMER_ID,ORDER_DATE,QUANTITY) VALUES (1, 1, '2021-04-01',8);
INSERT INTO BOOK_ORDER  (BOOK_ID,CUSTOMER_ID,ORDER_DATE,QUANTITY) VALUES (1, 1, '2021-04-01',8);
INSERT INTO BOOK_ORDER  (BOOK_ID,CUSTOMER_ID,ORDER_DATE,QUANTITY) VALUES (2, 1, '2021-05-01',9);
INSERT INTO BOOK_ORDER  (BOOK_ID,CUSTOMER_ID,ORDER_DATE,QUANTITY) VALUES (1, 1, '2021-06-01',4);
INSERT INTO BOOK_ORDER  (BOOK_ID,CUSTOMER_ID,ORDER_DATE,QUANTITY) VALUES (2, 1, '2021-07-01',3);