CREATE TABLE CUSTOMER(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR (255) NOT NULL,
    LAST_NAME VARCHAR (255) NOT NULL,
    EMAIL VARCHAR (255) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE BOOK(
     ID BIGINT NOT NULL AUTO_INCREMENT,
     BOOK_NAME VARCHAR (255) NOT NULL,
     AUTHOR VARCHAR (255) NOT NULL,
     ISBN VARCHAR (255) NOT NULL,
     STOCK_SIZE BIGINT NOT NULL,
     PRICE DOUBLE NOT NULL,
     PRIMARY KEY(ID)
);

CREATE TABLE BOOK_ORDER(
      ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
      BOOK_ID BIGINT NOT NULL,
      CUSTOMER_ID BIGINT NOT NULL,
      ORDER_DATE DATE NOT NULL,
      QUANTITY BIGINT NOT NULL
);